export const cardData = [
  {
    img: "images/photo-1557800636-894a64c1696f.jpeg",
    title: "Don’t be afraid",
    author_1: "Megan Anderson",
    author_2: "Lauren Langford",
    classname: "tag_hash_post_card_pool",
    btntext: "story",
  },
  {
    img: "images/photo-1533848052694-c716c6530f9c--WqbnBa.jpeg",
    title: "Anyone can hold the helm when the sea is calm",
    author_1: "Megan Anderson",
    author_2: "Charles Barrett",
    classname: "tag_hash_post_card_aqua",
    btntext: "home",
  },
  {
    img: "images/photo-1582020738577-2e7a48043902.jpeg",
    title: "You have to fight to reach your dream",
    author_1: "Megan Anderson",
    author_2: "",
    classname: "tag_hash_post_card_rose",
    btntext: "products",
  },
  {
    img: "images/photo-1580636521086-7b0c742dd567--lijMxb.jpeg",
    title: "Cuisine is a mirror, reflecting the culture",
    author_1: "Victoria West",
    author_2: "Patricia Jenkins",
    classname: "tag_hash_post_card_peach",
    btntext: "Creative",
  },
  {
    img: "images/photo-1579618385552-046edd29f899.jpeg",
    title: "Being unique is better than being perfect",
    author_1: "Megan Anderson",
    author_2: "",
    classname: "tag_hash_post_card_cream",
    btntext: "Home",
  },
];
